#!/usr/bin/env bash

# Export environment variables
export $(grep -v '^#' .env | xargs)

# Deactivate Symfony deprecation warning
export SYMFONY_DEPRECATIONS_HELPER=weak

echo "Running codeception unit tests" && vendor/bin/codecept run unit --coverage --coverage-html &&
echo "Running codeception tests..." && vendor/bin/codecept --env=dev run
