#!/usr/bin/env bash

set -x

export APP_ENV=test

bin/console doctrine:schema:drop --force &&
bin/console doctrine:schema:create &&
bin/console doctrine:fixtures:load --purge-with-truncate --no-interaction

composer test-coverage