services:
    app:
        image: ghcr.io/soebbing/cistern-level-tracker/app:latest
        container_name: cistern-tracker-app
        restart: always
        working_dir: /app
        volumes:
            - ./var:/app/var
        environment:
            VIRTUAL_HOST: cistern-tracker.handcoding.de
            APP_ENV: prod
            APP_SECRET: f7aaa4676049342a25ce17aa8df9af97
            DATABASE_URL: sqlite:////app/var/cistern.sqlite?charset=UTF8
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=web'
            - 'traefik.http.routers.cistern_tracker.entrypoints=http'
            - 'traefik.http.routers.cistern_tracker.rule=Host(`cistern-tracker.example`, `cistern-tracker.handcoding.de`)'
            - 'traefik.http.routers.cistern_tracker.service=cistern_tracker_service@docker'
            - 'traefik.http.services.cistern_tracker_service.loadbalancer.server.port=8000'
        networks:
            web:

networks:
    web:
        external: true