version: "3.3"

services:
    app:
        build:
            context: .
            dockerfile: dev-ops/Dockerfile
        container_name: cistern-tracker-app
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - 80:8000
        user: "1000:1000"