services:
    app:
        build:
            context: .
            dockerfile: dev-ops/Dockerfile
        image: cisterntracker_app:latest
        container_name: cistern-tracker-app
        ports:
            - "80:8000"
        user: "1000:1000"
        volumes:
        -  ./:/app