name: Build docker image
description: 'Build the ready-to-run Docker image'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

runs:
  using: 'docker'
  image: 'Dockerfile'
  needs: tests