name: PHP analysis & tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run code analysis
      run: .github/code-analysis

    - name: Run tests
      run: .github/tests

